#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libldap5/i386/Makefile
#

include ../Makefile.com

all: $(LIBS)
install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
