#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2017 Hayashi Naoyuki
#

SOURCE_DIR=$(EXTRA)/binutils

CONFIG_CFLAGS= -Wno-error=unused-value -Wno-error=sign-compare
CONFIG_ARGS= --disable-nls --with-sysroot
CONFIG_ARGS+= --target=$(MACH)-solaris2.10
CONFIG_ARGS+= --prefix=$(CROSS_TOOLS)
CONFIG_ARGS+= --enable-initfini-array
CONFIG_ARGS+= --disable-gdb
MAKE_ARGS=-j MAKEINFO=true

include ../Makefile.oss
